WITH BASE AS (
SELECT
  RAW_ECOM.PUBLIC.PRODUCTS.IS_REVIEWED,
  RAW_ECOM.PUBLIC.PRODUCTS.IS_CLOSEOUT,
  ANALYTICS.PUBLIC.SKUS.SEGMENT_NAME,
  ANALYTICS.PUBLIC.SKUS.BRAND_NAME,
  RAW_ECOM.PUBLIC.PRODUCTS.ID AS PAGE_ID,
  RAW_ECOM.PUBLIC.PRODUCTS.DISPLAY_NAME,
  RAW_ECOM.PUBLIC.RAW_SKUS.VENDOR_SKU,
  RAW_ECOM.PUBLIC.RAW_SKUS.MFG_PART_NUMBER,
  RAW_ECOM.PUBLIC.RAW_SKUS.PRICE_RETAIL,
  RAW_ECOM.PUBLIC.RAW_SKUS.PRICE_RETAIL_MAP,
  RAW_ECOM.PUBLIC.RAW_SKUS.PRICE_WHOLESALE,
  RAW_ECOM.PUBLIC.PRODUCTS.SALES
 
  FROM 
  RAW_ECOM.PUBLIC.PRODUCTS      

  LEFT JOIN
  ANALYTICS.PUBLIC.SKUS
  ON
  ANALYTICS.PUBLIC.SKUS.PRODUCT_ID = RAW_ECOM.PUBLIC.PRODUCTS.ID

  LEFT JOIN
  RAW_ECOM.PUBLIC.RAW_SKUS
  ON 
  RAW_ECOM.PUBLIC.RAW_SKUS.ID = ANALYTICS.PUBLIC.SKUS.ID
  
  WHERE SEGMENT_NAME IN ('Dirt', 'UTV/ATV')
  AND RAW_ECOM.PUBLIC.PRODUCTS.IS_BLEMISHED = FALSE
  AND RAW_ECOM.PUBLIC.PRODUCTS.IS_OEM = FALSE
  
  )
SELECT *
FROM BASE;
  
  