WITH BASE AS(
  SELECT
  PUBLIC.SKUS.MFG_PART_NUMBER AS MFG,
  PUBLIC.SKUS.PRODUCT_ID AS PAGE_ID,
  PUBLIC.SKUS.BRAND_NAME,
  PUBLIC.SKUS.PRODUCT_DISPLAY_NAME,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',1) AS MAKE,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',2) AS MODEL,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',3) AS YEAR,
  CONCAT ('http://www.revzilla.com/admin/products/edit/',PAGE_ID) AS PAGE_URL
  
  FROM 
  ANALYTICS.PUBLIC.SKUS
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.PRODUCT_APPLICATIONS  
  ON
  PRODUCT_APPLICATIONS.PRODUCT_ID = PUBLIC.SKUS.PRODUCT_ID
  
  LEFT JOIN
  ANALYTICS.PUBLIC.VEHICLES
  ON 
  VEHICLES.ID = PRODUCT_APPLICATIONS.VEHICLE_ID

)
SELECT
*
FROM BASE
-- WHERE MFG IN ('PART NUMBER','PART NUMBER','PART NUMBER');