WITH BASE AS(
  SELECT
  PRODUCTS.ID AS PAGE_ID,
  BRANDS.BRAND_NAME AS BRAND,
  PRODUCTS.DISPLAY_NAME,
  PRODUCT_TYPES.NAME AS PRODUCT_TYPE,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',1) AS MAKE,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',2) AS MODEL,
  split_part(VEHICLES.FULL_NAME_REFERENCE,'|',3) AS YEAR,
  CONCAT ('http://www.revzilla.com/admin/products/edit/',PAGE_ID) AS PAGE_URL
  
  FROM 
  ANALYTICS.PUBLIC.PRODUCTS
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.PRODUCT_APPLICATIONS  
  ON
  PRODUCT_APPLICATIONS.PRODUCT_ID = PRODUCTS.ID 
  
  LEFT JOIN
  ANALYTICS.PUBLIC.VEHICLES
  ON 
  VEHICLES.ID = PRODUCT_APPLICATIONS.VEHICLE_ID
  
  LEFT JOIN
  ANALYTICS.PUBLIC.PRODUCT_TYPES
  ON
  PRODUCT_TYPES.PRODUCT_TYPE_ID = APPAREL_TYPE
  
  LEFT JOIN
  ANALYTICS.PUBLIC.BRANDS
  ON
  ANALYTICS.PUBLIC.BRANDS.BRAND_ID = PRODUCTS.BRAND_ID
 

  WHERE PUBLIC.PRODUCTS.IS_CLOSEOUT = FALSE
  AND PRODUCTS.IS_ACTIVE = TRUE
  AND PRODUCTS.IS_REVIEWED = TRUE
  AND PRODUCTS.IS_BLEMISHED = FALSE
  AND PRODUCTS.IS_APPLICATION = TRUE
  AND PRODUCTS.IS_DELETED = FALSE
  AND PRODUCTS.SEGMENT_NAME NOT IN ('OEM')

)
SELECT *
FROM BASE;