WITH BASE AS(
  SELECT
  RAW_ECOM.PUBLIC.SKUS.ID AS SKU,
  RAW_ECOM.PUBLIC.PRODUCTS.ID AS PAGEID,
  RAW_ECOM.PUBLIC.BRANDS.NAME AS BRAND,
  RAW_ECOM.PUBLIC.PRODUCTS.DISPLAY_NAME,
  RAW_ECOM.PUBLIC.VEHICLES.FULL_NAME_REFERENCE
  FROM 
  RAW_ECOM.PUBLIC.PRODUCTS
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.PRODUCT_APPLICATIONS  
  ON
  RAW_ECOM.PUBLIC.PRODUCT_APPLICATIONS.PRODUCT_ID = RAW_ECOM.PUBLIC.PRODUCTS.ID 
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.VEHICLES
  ON 
  RAW_ECOM.PUBLIC.VEHICLES.ID = RAW_ECOM.PUBLIC.PRODUCT_APPLICATIONS.VEHICLE_ID
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.SKUS
  ON 
  RAW_ECOM.PUBLIC.SKUS.PRODUCT_ID = RAW_ECOM.PUBLIC.PRODUCTS.ID
  
  LEFT JOIN
  RAW_ECOM.PUBLIC.BRANDS
  ON
  RAW_ECOM.PUBLIC.BRANDS.ID = RAW_ECOM.PUBLIC.PRODUCTS.BRAND_ID
  
  WHERE RAW_ECOM.PUBLIC.PRODUCTS.BRAND_ID IN (572, 17973, 17974)
  AND RAW_ECOM.PUBLIC.PRODUCTS.IS_BLEMISHED = FALSE
  AND SKU IS NOT NULL

)
SELECT SKU, PAGEID, BRAND, DISPLAY_NAME,
split_part(FULL_NAME_REFERENCE,'|',1) Make,
split_part(FULL_NAME_REFERENCE,'|',2) Model,
split_part(FULL_NAME_REFERENCE,'|',3) Year
FROM BASE;