SELECT 
MFG_PART_NUMBER
,PRODUCT_DISPLAY_NAME
,PRICE_RETAIL
,PRICE_WHOLESALE
,BRAND_NAME
,ID AS SKU_ID
,PRODUCT_ID

FROM PUBLIC.SKUS
WHERE BRAND_NAME IN ('Kawasaki','Yamaha','Honda','Yamaha')
AND PRICE_RETAIL < 2.01
;